export const cuentosA2 = {
  Mari: 'Mari era una niña muy golosa. Un día encontró 5 euros. Se compró un helado',
  
  Lucas: 'Lucas era un niño curioso y aventurero. Un día, encontró un mapa en el desván de su abuela. El mapa tenía dibujos misteriosos y una X que marcaba un lugar desconocido. Lucas decidió emprender un viaje en busca del tesoro que el mapa prometía. Tomó su mochila, metió algunas galletas y una botella de agua, y salió de casa sin decirle a nadie. Caminó durante horas, siguiendo las pistas del mapa. Cruzó un puente, exploró un bosque y llegó a una playa desierta. Allí, encontró una cueva escondida. Dentro de la cueva, descubrió un cofre brillante. Con cuidado, lo abrió y encontró una colección de piedras de colores. No era un tesoro de oro, pero a Lucas le pareció hermoso. Satisfecho con su hallazgo, Lucas regresó a casa antes de que anocheciera. Le contó a su abuela sobre su emocionante aventura y le mostró las piedras que había encontrado. Ella le sonrió y le dijo que esas piedras eran más valiosas que cualquier tesoro. Lucas aprendió que las mejores aventuras no siempre implican riquezas, sino descubrimientos y recuerdos especiales',

  Tom: 'Había una vez un niño llamado Tom. Un día soleado, Tom decidió hacer un picnic en el parque con su familia. Empacaron una canasta llena de comida deliciosa, como sándwiches, frutas y galletas. También llevaron una manta para sentarse.Cuando llegaron al parque, encontraron un lugar bajo un árbol grande y extendieron la manta. Todos se sentaron y comenzaron a disfrutar de su comida. Tom compartió su sándwich con su perro, Max, que estaba muy emocionado por el picnic.Después de comer, Tom y su hermanita Lucy jugaron a atrapar una pelota. Rieron mucho y se lo pasaron muy bien. Mientras tanto, los padres de Tom descansaron en la manta, disfrutando del hermoso día.Finalmente, cuando el sol comenzó a ponerse, todos recogieron sus cosas y volvieron a casa. Tom estaba cansado pero feliz. Le dijo a su mamá que ese había sido el mejor día de picnic de su vida.Y así, Tom y su familia pasaron un día maravilloso juntos en el parque. Fue un día que siempre recordarían.',

  Ana: 'Ana vivía en una pequeña granja en el campo. Un día, decidió salir a explorar y ayudar a sus padres con las tareas diarias. Ana tenía un gato llamado Tito, que la siguió mientras caminaba por la granja.Primero, Ana fue al establo, donde vio a las vacas. Ayudó a su padre a darles de comer y les dio agua fresca. Las vacas parecían contentas y mugieron alegremente.Luego, Ana fue al gallinero y recogió huevos de las gallinas. Tenía que ser cuidadosa para no romper ninguno. Las gallinas cacareaban mientras Ana les agradecía por los huevos.Después, Ana fue al jardín y ayudó a su mamá a recoger verduras. Juntos cosecharon zanahorias, tomates y calabacines. Ana notó lo coloridas y frescas que eran las verduras.Por la tarde, Ana y Tito se sentaron en el porche de la casa. Comieron una deliciosa comida con las verduras que habían recogido. Estaban agotados pero felices. Ana miró el atardecer y pensó en lo hermosa que era su vida en la granja.Y así, Ana pasó un día emocionante en su granja, aprendiendo a cuidar de los animales y disfrutando de la naturaleza. Era un día lleno de aventuras y amor por su hogar en el campo',

  La_sorpresa_de_Luis: 'Luis era un niño de 8 años que vivía en un pequeño pueblo. Un día, mientras paseaba por el bosque cerca de su casa, encontró un pequeño pájaro herido. Lo recogió con cuidado y decidió llevarlo a casa. Luis puso al pájaro en una caja con un poco de comida y agua.Cada día, revisaba cómo se encontraba y le hablaba para que se sintiera acompañado.Con el tiempo, el pájaro comenzó a recuperarse y a confiar en Luis.Una mañana, cuando Luis fue a ver al pájaro, se dio cuenta de que ya podía volar.Con una mezcla de alegría y tristeza, abrió la caja y el pájaro salió volando hacia el cielo. Luis se sintió triste por dejar ir a su amigo, pero sabía que era lo mejor para el pájaro.Esa tarde, mientras Luis estaba en el jardín, el pájaro regresó y aterrizó en su hombro. Parecía agradecido por la ayuda de Luis y quería estar cerca de él. Desde ese día, el pájaro se convirtió en su fiel compañero y juntos vivieron muchas aventuras.La sorpresa de Luis fue que, al ayudar al pájaro, encontró un amigo leal que siempre estaría a su lado.Espero que este cuento te haya gustado y que haya sido adecuado para tu nivel. Si tienes alguna otra pregunta o solicitud, no dudes en decírmelo.',

  El_regalo_sorpresa: 'Un día, Pablo encontró un huevo en el jardín de su abuela. Lo recogió y cuidó de él con mucho cariño. Después de unos días, el huevo se rompió y salió un pequeño pollito. Pablo se alegró mucho y decidió llamarlo "Coco". Juntos, Pablo y Coco vivieron muchas aventuras. Coco se convirtió en el mejor amigo de Pablo y le dio el regalo más hermoso: la amistad',

  El_picnic_en_el_parque : 'Un sábado por la mañana, Laura y su familia decidieron hacer un picnic en el parque. Prepararon sándwiches, frutas y refrescos. Llevaron una manta y se instalaron cerca de un lago. Mientras comían, vieron patos nadando en el lago y escucharon el canto de los pájaros. Después del picnic, jugaron a atrapar una pelota y reían mucho. Laura se sentía feliz. Al final del día, recogieron todo y regresaron a casa. Laura estaba cansada pero contenta. Prometieron hacer más picnics en el futuro'
}

export const bilingue = [
  {
    titulo:'Lucas',
    esp: 'Lucas era un niño curioso y aventurero. Un día, encontró un mapa en el desván de su abuela. El mapa tenía dibujos misteriosos y una X que marcaba un lugar desconocido. Lucas decidió emprender un viaje en busca del tesoro que el mapa prometía. Tomó su mochila, metió algunas galletas y una botella de agua, y salió de casa sin decirle a nadie. Caminó durante horas, siguiendo las pistas del mapa. Cruzó un puente, exploró un bosque y llegó a una playa desierta. Allí, encontró una cueva escondida. Dentro de la cueva, descubrió un cofre brillante. Con cuidado, lo abrió y encontró una colección de piedras de colores. No era un tesoro de oro, pero a Lucas le pareció hermoso. Satisfecho con su hallazgo, Lucas regresó a casa antes de que anocheciera. Le contó a su abuela sobre su emocionante aventura y le mostró las piedras que había encontrado. Ella le sonrió y le dijo que esas piedras eran más valiosas que cualquier tesoro. Lucas aprendió que las mejores aventuras no siempre implican riquezas, sino descubrimientos y recuerdos especiales',
    ing:"Lucas was a curious and adventurous child. One day, he found a map in his grandmother's attic. The map had mysterious drawings and an X marking an unknown location. Lucas decided to embark on a journey in search of the treasure that the map promised. He took his backpack, put some cookies and a bottle of water, and left the house without telling anyone. He walked for hours, following the clues on the map. He crossed a bridge, explored a forest and arrived at a deserted beach. There, he found a hidden cave. Inside the cave, he discovered a glowing chest. Carefully, he opened it and found a collection of colored stones. It wasn't a treasure of gold, but Lucas thought it was beautiful. Satisfied with his find, Lucas returned home before nightfall. He told his grandmother about his exciting adventure and showed her the stones he had found. She smiled at him and told him that those stones were more valuable than any treasure. Lucas learned that the best adventures don't always involve riches, but rather special discoveries and memories"
  },
  {
    titulo:'mari',
    esp: 'Mari era una niña muy golosa. Un día encontró 5 euros. Se compró un helado',
    ing: 'Mari was a very sweet girl. One day he found 5 euros. He bought an ice cream',
  }
]
export const titulos = bilingue.map(e=>e.titulo)
console.log(titulos)

